server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://135.181.255.229:8080/realms/demo-realm
          jwk-set-uri: http://135.181.255.229:8080/realms/demo-realm/protocol/openid-connect/certs

      client:
        registration:
          keycloak:
            client-id: demo-client
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://135.181.255.229:8080/realms/demo-realm
            user-name-attribute: preferred_username

jwt:
  auth:
    converter:
      resource-id: demo
      principle-attribute: preferred_username
