server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://135.181.255.229:8080/realms/demo-realm
          jwk-set-uri: http://135.181.255.229:8080/realms/demo-realm/protocol/openid-connect/certs

      client:
        registration:
          keycloak:
            client-id: demo-client
            client-secret: MhiXS7ojHJGr35h14JyVvmjx2mtUx8eC
            scope:
              - openid
              - profile
              - email
            redirect-uri: "http://135.181.255.229:8081/login/oauth2/code/keycloack"
        provider:
          keycloak:
            issuer-uri: http://135.181.255.229:8080/realms/demo-realm


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
