server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: demo-client
            client-secret: MhiXS7ojHJGr35h14JyVvmjx2mtUx8eC
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://135.181.255.229:8080/realms/demo-realm
            authorization-uri: http://135.181.255.229:8080/realms/demo-realm/protocol/openid-connect/auth
            token-uri: http://135.181.255.229:8080/realms/demo-realm/protocol/openid-connect/token
            user-info-uri: http://135.181.255.229:8080/realms/demo-realm/protocol/openid-connect/userinfo
            jwk-set-uri: http://135.181.255.229:8080/realms/demo-realm/protocol/openid-connect/certs
            user-name-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG